### ISSUE TITLE
Contribution a new work on large-vision model for medical images?

### ISSUE THREAD

**Issue by duyhominhnguyen** [awaisrauf/Awesome-CV-Foundational-Models#1]
Dear authors

Thanks for your great GitHub and the survey paper. I want to ask if it's possible to add this work [LVM-Med](https://arxiv.org/abs/2306.11925) to your repo. The paper is working on the large-vision model, focused on medical images. 

Duy

**Comment by Muzammal-Naseer** [comment]
Hi, 

Thank you for bringing our attention to this work. We have added it.
