### ISSUE TITLE
Closely Related Works

### ISSUE THREAD

**Issue by lxtGH** [awaisrauf/Awesome-CV-Foundational-Models#2]
Hi! It is a nice and comprehensive survey on vision foundation model.

Our group also carry out several research and survey.

1. Open Vocabulary Learning Survey. [paper](https://arxiv.org/abs/2306.15880), [code](https://github.com/jianzongwu/Awesome-Open-Vocabulary)

2. Visual Prompting in Point Cloud. [paper](https://arxiv.org/abs/2306.08659), [code](https://github.com/fanglaosi/Point-In-Context)

3. Transformer-Based Visual Segmentation: A Survey. [paper](https://arxiv.org/abs/2304.09854),  [code](https://lxtgh.github.io/project/pub/)

Could you add our works in your paper and repo?

We would also add your work in our paper and code. 

Thanks!!!

**Comment by awaisrauf** [comment]
Added. Thanks for the suggestion.
